version: '3.8'

services:
  kedro:
    build: .
    volumes:
      - .:/app
    working_dir: /app/src/iris_pipeline
    command: ["kedro", "run"]

  iris-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - kedro
    command: ["python", "api.py"]
